version: '3.1'

services:
  db:
    image: mysql:8.0.37
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./sqlfiles:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  server-py:
    image: server-py
    restart: always
    volumes:
      - ./server-py:/server-py
    build: 
      context: ./server-py
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=myregistrationdb
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    depends_on:
      - db
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8001

  react:
    image: react
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=8001
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - server-py
    command: npm start
