# Use root/example as user/password credentials
version: '3.1'

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    ports:
      - 3307:3307
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
  server:
    image: nodejs
    volumes:
      - ./server:/server
      - /server/node_modules
    build:
      context: .
      dockerfile: ./server/DockerfileNodejs
    restart: always
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT=8000
    depends_on:
      - db
    command: node server.js
  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      <<: *common-variables
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    depends_on:
      - server
    command: npm start

